export const ENGLISH_LANGUAGE_ID = process.env.NEXT_PUBLIC_ENGLISH_LANGUAGE_ID
export const ANONYMOUS_USER_ID = process.env.NEXT_PUBLIC_ANONYMOUS_USER_ID
export const ANONYMOUS_USER_EMAIL = process.env.NEXT_PUBLIC_ANONYMOUS_USER_EMAIL
export const ALL_LANGUAGE_ID = process.env.NEXT_PUBLIC_ALL_LANGUAGE_ID