import "./globals.css";
import type { Metadata } from "next";
import { PT_Sans as ptsans } from "next/font/google";
import Providers from "./Providers";
import { authOptions } from "./auth";
import { getServerSession } from "next-auth";
import Header from "@/components/Common/Header";
import { Toaster } from "react-hot-toast";

const ptSans = ptsans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={ptSans.className}>
        <Providers session={session}>
          <Header session={session} />

          {children}
          {auth}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
